### ISSUE TITLE
[Question]using odbogm with java8  

### ISSUE THREAD

**Issue by gunaskr** [mdre/odbogm#1]
Thanks for your contribution.
Planning to use it for one of our project. However the maven jar was
compiled and built with java 11 it seems. I'm trying to build your
source to 1.8 target but seems like you have used VirtualMachine class
with is available in java 11 rt. It seems like you are doing this for
instrumentation. I'm not sure though. Is this part necessary for the
mapping to work? If so is there any workaround i could do?

**Comment by gunaskr** [comment]
i was able to figure it out.

**Comment by mdre** [comment]
Hi.

We moved last year all the code to J11 in all project due to the need
to evolve, and some things has changed in the code. Specially the use
of tools.jar library that's not exist anymore.
The ODBOGM has two part. The driver and an agent that made and
instrumentation of the classes.
The Agent intercept the class load and add an interface and it
implementation methods to every class marked as with @Entity. This
parts is very important because the automatic detection of dirty
object is done through the class instrumentation to speed up the work.
The OGM then use the class and dialog with it through the interface
and the CGLib.
With J8 this was done with a library that was a non-ofical part of the
JDK, called "tools.jar", but it was removed and the classes was moved
to the main branch.
The last version compiled with J8 of the odbogm was the 1.0.6 and the
Agent 1.0.4.
If you need to stay in J8, you could download the sources of that
versions and made a patch to the current version.
You need to patch the
net.odbogm.agent.TransparentDirtyDetectorAgent.java class in the
agent, and net.odbogm.SessionManage.java in the odbogm.
If the test pass all is ok! :D
but, I suggest to move on to OpenJDK 11 or Zulu 11 if you need support.

Good luck!  and send a mail if need something else.
